#!/usr/bin/env bash

# Check if an argument (bucket name) is provided
if [ -z "$1" ]; then
    echo "A bucket name is required. Example: ./bucket my-bucket-ab"
    exit 1
fi

BUCKET_NAME=$1

echo "aws s3api create-bucket --bucket $BUCKET_NAME"

aws s3api create-bucket --bucket "$BUCKET_NAME" --region us-east-1